# Generated by Django 5.0.6 on 2025-07-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_archivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='coment',
            field=models.TextField(verbose_name='Comentario'),
        ),
    ]
